-- Chạy ở CDB$ROOT
ALTER SESSION SET CONTAINER=CDB$ROOT;

CREATE USER C##DEBEZIUM_USER IDENTIFIED BY "Abc12345"
DEFAULT TABLESPACE SYSTEM
TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK
PROFILE DEFAULT;

GRANT UNLIMITED TABLESPACE TO C##DEBEZIUM_USER;
GRANT CONNECT, CREATE SESSION TO C##DEBEZIUM_USER;

GRANT SELECT_CATALOG_ROLE TO C##DEBEZIUM_USER;
GRANT EXECUTE_CATALOG_ROLE TO C##DEBEZIUM_USER;
GRANT SELECT ANY DICTIONARY TO C##DEBEZIUM_USER;
GRANT FLASHBACK ANY TABLE TO C##DEBEZIUM_USER;
GRANT SELECT ANY TRANSACTION TO C##DEBEZIUM_USER;

GRANT EXECUTE ON DBMS_LOGMNR TO C##DEBEZIUM_USER;
GRANT EXECUTE ON DBMS_LOGMNR_D TO C##DEBEZIUM_USER;
GRANT LOGMINING TO C##DEBEZIUM_USER;