-- Chuyển vào PDB
ALTER SESSION SET CONTAINER=ORCLPDB1;

-- Cho phép DEBEZIUM user tạo schema object
GRANT CONNECT, RESOURCE TO C##DEBEZIUM_USER;
ALTER USER C##DEBEZIUM_USER QUOTA UNLIMITED ON USERS;

-- Tạo schema TESTDB (Oracle: user = schema)
CREATE USER TESTDB IDENTIFIED BY "Abc12345"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
ACCOUNT UNLOCK;
GRANT CONNECT, RESOURCE TO TESTDB;
ALTER USER TESTDB QUOTA UNLIMITED ON USERS;

-- Tạo bảng ORDERS trong schema TESTDB
ALTER SESSION SET CURRENT_SCHEMA = TESTDB;

CREATE TABLE PRODUCT (
  SHOP_CODE VARCHAR2(20) NOT NULL,
  JAN_CODE VARCHAR2(13) NOT NULL,
  QUANTITY NUMBER(8),
  PRICE NUMBER(10, 2),
  CREATED_DATE DATE DEFAULT SYSDATE,
  UPDATED_TS TIMESTAMP(6) ,
  EXPIRY_TS TIMESTAMP(6),
  PRODUCT_NAME VARCHAR2(100),
  STATUS CHAR(1),
  DESCRIPTION CLOB,
  CONSTRAINT PK_PRODUCT PRIMARY KEY (SHOP_CODE, JAN_CODE)
);

INSERT INTO PRODUCT (SHOP_CODE, JAN_CODE, QUANTITY, PRICE,CREATED_DATE, UPDATED_TS, EXPIRY_TS, PRODUCT_NAME, STATUS, DESCRIPTION)
VALUES ('SHOP001', '1234567890123', 100, 100.00, SYSDATE, NULL, SYSDATE, 'Product A', 'A', 'Description for Product A');

INSERT INTO PRODUCT (SHOP_CODE, JAN_CODE, QUANTITY, PRICE,CREATED_DATE, UPDATED_TS, EXPIRY_TS, PRODUCT_NAME, STATUS, DESCRIPTION)
VALUES ('SHOP001', '4567890123456', 200, 200.00, SYSDATE, NULL, SYSDATE, 'Product B', 'A', 'Description for Product B');


COMMIT;
