ALTER SESSION SET CONTAINER=CDB$ROOT;

SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;

ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
alter database add supplemental log data (all) columns;
alter database add supplemental log data (primary key) columns;

-- ALTER DATABASE DROP SUPPLEMENTAL LOG DATA;
-- ALTER DATABASE DROP SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
-- ALTER DATABASE DROP SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;


ALTER DATABASE FORCE LOGGING;
ALTER SYSTEM SWITCH LOGFILE;
